name: Build and deploy

on:
  push:
    branches:
      - master
        
env:
  PROJECT_NAME: frostorchunter
        
jobs:
  build:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-24.04
    strategy:
      matrix: 
        targetPlatform:
          - WebGL
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-

      - name: Activate Unity License
        uses: game-ci/unity-request-activation-file@v2
        id: license
        with:
            unityVersion: 6000.0.36f1
            username: ${{ secrets.UNITY_EMAIL }}
            password: ${{ secrets.UNITY_PASSWORD }}
           
      - uses: game-ci/unity-builder@v4
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: ${{ env.PROJECT_NAME }}
          projectPath: .
          unityVersion: 6000.0.36f1

          
      - uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: html5
          ITCH_GAME: "Cat Tap Frenzy"
          ITCH_USER: Cvancer
          PACKAGE: build/${{ matrix.targetPlatform }}
